### ISSUE TITLE
Undefined variable: g:plug_config_lua_dir 

### ISSUE THREAD

**Issue by kqvanity** [ouuan/vim-plug-config#4]
I've setup the other `g:plug_config_vim_dir` variable, as i only have vimscript configuration. the plugin still raises a a long thread of this `Undefined variable ...` error messages. I guess this is a bug, as i guess only one configuration should suffice i.e. vimrc file in this case.
I'm hoping this plugin isn't confined to neovim (event though it's stated as neovim being a requirement, but i'll try my luck in here)

**Comment by ouuan** [comment]
As I wrote this plugin a long time ago, I didn't remember what's the exact reason for requiring Neovim. Maybe the error message could be helpful to determine the reason.

However, as I use Neovim, I have no plan to support Vim without either a PR for it or enough users of this plugin.

**Comment by kqvanity** [comment]
Understandable. No problem.

**Comment by Song-Tianxiang** [comment]
I have modify the plugin to work on vim. check [here](https://github.com/Song-Tianxiang/vim-plug-config)
